name: Testit

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  workflow_dispatch:
    inputs:
      jdkVersion:
        description: 'JDK version'
        required: true
        default: '16'

env:
  JDK_VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.jdkVersion || '16' }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}

      - name: Print Java version
        shell: bash
        run: |
          java -version
          which javac

      - name: Run jbang
        uses: jbangdev/jbang-action@v0.70.0
        with:
          script: helloworld.java
          jbangargs: --verbose
