name: Testit

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  workflow_dispatch:
    inputs:
      jdkVersion:
        description: 'JDK version'
        required: true
        default: '16'
      adopt:
        description: 'Use AdoptOpenJDK'
        required: true
        default: 'false'

env:
  JDK_VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.jdkVersion || '16' }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Zulu JDK
        uses: actions/setup-java@v1
        if: ${{ github.event.inputs.adopt == 'false' }}
        with:
          java-version: ${{ env.JDK_VERSION }}

      - name: Set up AdoptOpenJDK
        uses: joschi/setup-jdk@v2.3.0
        if: ${{ github.event.inputs.adopt == 'true' }}
        with:
          java-version: ${{ env.JDK_VERSION }}

      - name: Print Java version
        shell: bash
        run: |
          java -version
          echo 'Location of javac:'
          which javac
          # echo 'JAVA_HOME=' >> $GITHUB_ENV

      - name: Copy JDK
        shell: bash
        run: |
          pwd
          mkdir .jdk
          cp -va ${JAVA_HOME}/* .jdk/
          #echo 'JAVA_HOME=/github/workspace/.jdk' >> $GITHUB_ENV
          #echo "JAVA_HOME: ${JAVA_HOME}"

      - name: Run jbang
        uses: jbangdev/jbang-action@v0.70.0
        with:
          script: helloworld.java
          jbangargs: --verbose
        env:
          JAVA_HOME: '/github/workspace/.jdk'
